# Generated by Django 5.1.7 on 2025-03-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
            preserve_default=False,
        ),
    ]
